### ISSUE TITLE
install command fails on docker 1.13.0-rc3

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr#186]
The `install` command for Lagom applications is failing on Docker 1.13.0-rc3:

**Error**

```
[info] Main Java API documentation successful.
[info] Packaging /Users/ignasi/git/projects/lightbend/samples-lagom/online-auction-java/transaction-api/target/scala-2.11/transactionapi_2.11-1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info] Packaging /Users/ignasi/git/projects/lightbend/samples-lagom/online-auction-java/web-gateway/target/scala-2.11/webgateway_2.11-1.0-SNAPSHOT-sans-externalized.jar ...
[info] Done packaging.
[info] Bundle has been created: /Users/ignasi/git/projects/lightbend/samples-lagom/online-auction-java/web-gateway/target/bundle/webgateway-v1-1282e8aad55d711445965d576a600e9ac1c40e68b2ac6807912f6061ed5295f7.zip
Error response from daemon: Invalid filter '"name'
[error] ({.}/*:install) java.lang.IllegalStateException: Please first start the sandbox using 'sandbox run'.
[error] Total time: 75 s, completed Dec 14, 2016 4:28:20 PM
```

**Stacktrace**

```
java.lang.IllegalStateException: Please first start the sandbox using 'sandbox run'.
    at com.lightbend.conductr.sbt.ConductrPlugin$$anonfun$installTask$1$$anonfun$apply$3.apply$mcV$sp(ConductRPlugin.scala:179)
    at com.lightbend.conductr.sbt.ConductrPlugin$$anonfun$installTask$1$$anonfun$apply$3.apply(ConductRPlugin.scala:172)
    at com.lightbend.conductr.sbt.ConductrPlugin$$anonfun$installTask$1$$anonfun$apply$3.apply(ConductRPlugin.scala:172)
    at com.lightbend.conductr.sbt.ConductrPlugin$.com$lightbend$conductr$sbt$ConductrPlugin$$withProcessHandling(ConductRPlugin.scala:690)
    at com.lightbend.conductr.sbt.ConductrPlugin$$anonfun$installTask$1.apply(ConductRPlugin.scala:181)
    at com.lightbend.conductr.sbt.ConductrPlugin$$anonfun$installTask$1.apply(ConductRPlugin.scala:171)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] ({.}/*:install) java.lang.IllegalStateException: Please first start the sandbox using 'sandbox run'.
>
```

It seems that the `docker ps -q --filter="name=cond-"` command does not work with Docker 1.13.0-rc3 anymore. I haven't tested it yet with this Docker version but we possible can use this format instead:

```
docker ps -q --filter name=cond-
```

**Comment by markusjura** [comment]
This issue occurred on @ignasi35 machine.

**Comment by markusjura** [comment]
Another possible issue could be that @ignasi35 uses OSX 10.12.1 (Yosemite). Docker 1.1.13 does not support Yosemite anymore:

> from https://docs.docker.com/docker-for-mac/ "Starting with Docker for Mac stable release 1.13 (upcoming), and concurrent Beta releases, we will no longer address issues specific to OS X Yosemite 10.10. In future releases, Docker for Mac could stop working on OS X Yosemite 10.10 due to the deprecated status of this OS X version. We recommend upgrading to the latest version of macOS.”

**Comment by huntc** [comment]
Why are we not reporting this as an issue to Docker...? I'm fed up with their API changing...

**Comment by markusjura** [comment]
I am not sure yet if this is API change related. It could be also OS related given @ignasi35 uses macOS Yosemite which is not supported by Docker 1.1.13 anymore. I'd like to reproduce this error on the latest macOS version first. If the error doesn't occur then we can close this issue because Docker 1.1.13 requires newer macOS versions than Yosemite.

If the error also occurs on macOS then I'd like to know if we can still use a different format to retrieve the Docker container ids with Docker 1.1.13, e.g.:

```
docker ps -q --filter name=cond-
```

**Comment by ignasi35** [comment]
"Another possible issue could be that @ignasi35 uses OSX 10.12.1 (Yosemite)." 
should read
"Another possible issue could be that @ignasi35 uses OSX _10.10.5_ (Yosemite)."

The error occurred the same day I upgraded Docker Beta 1.13-rc2 to Docker Beta 1.13-rc3.

**Comment by markusjura** [comment]
Closing this issue because it was probably related to @ignasi35 environment and the ConductR 2.x.x in the sandbox is not running inside a Docker container anymore.
